In [11]:
# ============================================================
# CELL 1 — Mount Drive + install packages
# ============================================================

from pathlib import Path
import subprocess

IN_COLAB = False

try:
    from google.colab import drive
    IN_COLAB = True
except ImportError:
    pass

if IN_COLAB:
    drive.mount("/content/drive")

if IN_COLAB:
    get_ipython().system(
        "pip -q install speciesnet timm torch torchvision "
        "scikit-learn pandas matplotlib pillow requests tqdm"
    )

import os, re, json, math, time, random
from io import BytesIO
from collections import Counter

import requests
import numpy as np
import pandas as pd
from PIL import Image
from tqdm.auto import tqdm

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
import timm

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    f1_score,
    precision_recall_fscore_support,
    confusion_matrix,
    ConfusionMatrixDisplay,
)

import matplotlib.pyplot as plt

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", DEVICE)

Device: cpu

In [12]:
USE_GIT = True if IN_COLAB else False

In [13]:
REPO_URL = "https://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@github.com/carolynruan/cs159.git"

if USE_GIT:
    REPO_ROOT = Path("/content/cs159")

    if not REPO_ROOT.exists():
        subprocess.run(
            ["git", "clone", REPO_URL, str(REPO_ROOT)],
            check=True,
        )

    ARTIFACT_ROOT = Path("/content/drive/MyDrive/cs159")

else:
    try:
        REPO_ROOT = Path(__file__).resolve().parent
    except NameError:
        # notebook / interactive session
        REPO_ROOT = Path(".").resolve()

    ARTIFACT_ROOT = REPO_ROOT / "artifacts"

ARTIFACT_ROOT.mkdir(parents=True, exist_ok=True)

assert REPO_ROOT.exists(), f"Repo root does not exist: {REPO_ROOT}"

os.chdir(REPO_ROOT)

print("Repo:", REPO_ROOT)
print("Artifacts:", ARTIFACT_ROOT)

Repo: C:\dev\cs159
Artifacts: C:\dev\cs159\artifacts

 Experiment setup

In [14]:
from pathlib import Path
import sys
import pandas as pd

from lila_pipeline_helpers import (
    load_lila_suppl_data,
    select_bottom_percent_classes,
    serialize_class_targets,
    load_lila_train_split,
    sample_class_images,
    write_manifest,
)

In [15]:
suppl_df = load_lila_suppl_data(REPO_ROOT / "lila-suppl-data.csv")
suppl_df = suppl_df[suppl_df["count_train"] > 0].reset_index(drop=True)
suppl_df.to_csv(REPO_ROOT / "lila-suppl-data-pruned.csv", index=False)

In [16]:
def save_bottom_percentile(suppl_df, percentile=5.0):
    targets = select_bottom_percent_classes(
        suppl_df,
        percentile=percentile,
    )

    serialize_class_targets(targets, ARTIFACT_ROOT, stem=f"lila_bottom{int(percentile)}_targets")

    print(f"{len(targets)} classes selected")
    display(targets.head())

    train_df = load_lila_train_split(
        REPO_ROOT / "lila_splits" / "lila_splits_train.csv"
    )
    train_df = train_df[
        train_df["common_name"].isin(targets["common_name"])
    ].reset_index(drop=True)

    selection_rows = []

    for _, row in targets.iterrows():
        class_name = row["common_name"]

        class_df = train_df[train_df["common_name"] == class_name]

        selection_rows.append({
            "common_name": class_name,
            "num_source_images": len(class_df),
            "source_images": class_df["gs_filepath"].tolist(),
        })

    selection_df = pd.DataFrame(selection_rows)
    selection_df = selection_df[selection_df["num_source_images"] > 0].reset_index(drop=True)
    print(selection_df.size)
    write_manifest(
        selection_df,
        ARTIFACT_ROOT / f"lila_bottom{int(percentile)}_sources.csv",
    )

    selection_df.head()

In [17]:
save_bottom_percentile(suppl_df, percentile=5.0)

164 classes selected

,class,order,family,genus,species,common_name,count_train,count_validation,count_test
0,Mammalia,Pilosa,Myrmecophagidae,NaN,NaN,Anteater Family,1,0,0
1,Mammalia,Rodentia,Hystricidae,Atherurus,NaN,Atherurus Species,1,0,0
2,Aves,Passeriformes,Icteridae,Curaeus,curaeus,Austral Blackbird,1,0,0
3,Aves,Passeriformes,Hirundinidae,Hirundo,rustica,Barn Swallow,1,1,0
4,Aves,Passeriformes,Parulidae,Mniotilta,varia,Black-and-white Warbler,1,3,0

36

In [18]:
save_bottom_percentile(suppl_df, percentile=10.0)

288 classes selected

,class,order,family,genus,species,common_name,count_train,count_validation,count_test
0,Mammalia,Pilosa,Myrmecophagidae,NaN,NaN,Anteater Family,1,0,0
1,Mammalia,Rodentia,Hystricidae,Atherurus,NaN,Atherurus Species,1,0,0
2,Aves,Passeriformes,Icteridae,Curaeus,curaeus,Austral Blackbird,1,0,0
3,Aves,Passeriformes,Hirundinidae,Hirundo,rustica,Barn Swallow,1,1,0
4,Aves,Passeriformes,Parulidae,Mniotilta,varia,Black-and-white Warbler,1,3,0

75

In [21]:
save_bottom_percentile(suppl_df, percentile=20.0)

460 classes selected

,class,order,family,genus,species,common_name,count_train,count_validation,count_test
0,Mammalia,Pilosa,Myrmecophagidae,NaN,NaN,Anteater Family,1,0,0
1,Mammalia,Rodentia,Hystricidae,Atherurus,NaN,Atherurus Species,1,0,0
2,Aves,Passeriformes,Icteridae,Curaeus,curaeus,Austral Blackbird,1,0,0
3,Aves,Passeriformes,Hirundinidae,Hirundo,rustica,Barn Swallow,1,1,0
4,Aves,Passeriformes,Parulidae,Mniotilta,varia,Black-and-white Warbler,1,3,0

147